name: Generate Resume PDF

on:
  push:
    paths:
      - 'README.md'
    branches:
      - main
  workflow_dispatch:

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          pip install pyyaml
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra

      - name: Generate LaTeX from README
        run: |
          python3 .github/scripts/generate_latex.py
          
      - name: Build PDF
        run: |
          pdflatex -interaction=nonstopmode resume.tex
          pdflatex -interaction=nonstopmode resume.tex
          
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v3
        with:
          name: resume
          path: resume.pdf
          
      - name: Commit PDF
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add resume.pdf
          git commit -m "Update resume.pdf" || echo "No changes to commit"
          git push
